metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: train2017
  anno_path: annotations/person_keypoints_train2017.json
  dataset_dir: E:\dataset\4train/coco
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val2017
  anno_path: annotations/person_keypoints_val2017.json
  dataset_dir: E:\dataset\4train/coco
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/stuff_val2017.json # also support txt (like VOC's label_list.txt)
  dataset_dir: E:\dataset\4train/coco # if set, anno_path will be 'dataset_dir/anno_path'
