metric: COCO
num_classes: 25

TrainDataset:
  name: COCODataSet
  image_dir: train
  anno_path: annotations/detection_train.json
  dataset_dir: E:\dataset\4train\det/coco
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val
  anno_path: annotations/detection_val.json
  dataset_dir: E:\dataset\4train\det/coco
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/detection_val.json # also support txt (like VOC's label_list.txt)
  dataset_dir: E:\dataset\4train\det/coco # if set, anno_path will be 'dataset_dir/anno_path'
